name: Action test on MacOS

on:
  schedule:
    - cron: "0 4 * * MON-FRI" # Runs at 04:00 UTC
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/pull-request-action@main
        with:
          source_branch: "main"
          destination_branch: "test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}