name: Action test on Ubuntu

on:
  schedule:
    - cron: "0 2 * * MON-FRI" # Runs at 02:00 UTC
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/pull-request-action@main
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}