name: Action test on Windows

on:
  schedule:
    - cron: "0 6 * * MON-FRI" # Runs at 06:00 UTC
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/pull-request-action@main
        with:
          source_branch: "main"
          destination_branch: "test"
          github_token: ${{ secrets.GITHUB_TOKEN }}