name: Action test on Windows

on:
  schedule:
    - cron: "0 6 * * MON-FRI" # Runs at 06:00 UTC
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/pull-request-action@main
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}