name: Action test on Windows

on:
  schedule:
    - cron: "0 6 * * MON-FRI" # Runs at 06:00 UTC
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  windows-min:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/pull-request-action@main
        with:
          source_branch: "main"
          destination_branch: "test-windows-min"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-max:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/pull-request-action@main
        with:
          source_branch: "main"
          destination_branch: "test-windows-max"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "An automated PR"
          pr_reviewer: "GuillaumeFalourd"
          pr_assignee: "GuillaumeFalourd"
          pr_label: "test"
          pr_milestone: "Milestone 1"
          pr_draft: true
          pr_allow_empty: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}